# Generated by Django 4.0.2 on 2022-02-22 18:22

from django.db import migrations, models
import recipes.main.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=250, validators=[recipes.main.helpers.validate_string_is_separated_correctly]),
        ),
    ]
